#!/usr/bin/env bash
#display subdomains information

dns_config () {
    script=$(dig "$2"."$1" | awk '/ANSWER SECTION:/ {getline; print $1, $2, $NF}')
    echo "The subdomain $2 is a $script record and points to $NF"
}

if [ "$#" == 1 ]
then
    dns_config "$1" "www"
    dns_config "$1" "lb-01"
    dns_config "$1" "web-01"
    dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
    dns_config "$1" "$2"
fi